/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cgpa.calculator;

/**
 *
 * @author Ahmad Khan
 */
public class CGPAGUI extends javax.swing.JFrame {
    
    private double qualityPoints, gpa;
    private double qp1, qp2, qp3, qp4, qp5, qp6, totalQualityPoints;
    private int cre1, cre2, cre3, cre4, cre5, cre6, totalCreditHours;
    
    public CGPAGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblmarks = new javax.swing.JLabel();
        txtsubject1 = new javax.swing.JTextField();
        lblcredithours = new javax.swing.JLabel();
        lblsubject1 = new javax.swing.JLabel();
        lblsubject2 = new javax.swing.JLabel();
        lblsubject3 = new javax.swing.JLabel();
        lblsubject5 = new javax.swing.JLabel();
        lblsubject4 = new javax.swing.JLabel();
        lblsubject6 = new javax.swing.JLabel();
        txtcredit4 = new javax.swing.JTextField();
        txtcredit1 = new javax.swing.JTextField();
        txtcredit3 = new javax.swing.JTextField();
        txtcredit2 = new javax.swing.JTextField();
        txtsubject6 = new javax.swing.JTextField();
        txtcredit5 = new javax.swing.JTextField();
        txtsubject2 = new javax.swing.JTextField();
        txtsubject4 = new javax.swing.JTextField();
        txtsubject3 = new javax.swing.JTextField();
        txtsubject5 = new javax.swing.JTextField();
        txtcredit6 = new javax.swing.JTextField();
        lblgpa = new javax.swing.JLabel();
        txtgpa = new javax.swing.JTextField();
        btncalcgpa = new javax.swing.JButton();
        btnreset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("CGPA Calculator");

        lblmarks.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblmarks.setText("Marks");

        txtsubject1.setText("0");

        lblcredithours.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblcredithours.setText("Credit Hours");

        lblsubject1.setText("Subject 1");

        lblsubject2.setText("Subject 2");

        lblsubject3.setText("Subject 3");

        lblsubject5.setText("Subject 5");

        lblsubject4.setText("Subject 4");

        lblsubject6.setText("Subject 6");

        txtcredit4.setText("0");

        txtcredit1.setText("0");

        txtcredit3.setText("0");

        txtcredit2.setText("0");

        txtsubject6.setText("0");

        txtcredit5.setText("0");

        txtsubject2.setText("0");

        txtsubject4.setText("0");

        txtsubject3.setText("0");

        txtsubject5.setText("0");

        txtcredit6.setText("0");

        lblgpa.setText("GPA");

        txtgpa.setEditable(false);

        btncalcgpa.setText("Calculate");
        btncalcgpa.setToolTipText("");
        btncalcgpa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncalcgpaActionPerformed(evt);
            }
        });

        btnreset.setText("Reset");
        btnreset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnresetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblsubject1)
                    .addComponent(lblsubject2)
                    .addComponent(lblsubject3)
                    .addComponent(lblsubject5)
                    .addComponent(lblsubject4)
                    .addComponent(lblsubject6)
                    .addComponent(btncalcgpa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(lblmarks)
                    .addComponent(txtsubject1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubject6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubject2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubject4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubject3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtsubject5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(txtcredit4, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcredit1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcredit3, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcredit2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblcredithours)
                    .addComponent(txtcredit5, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcredit6, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(137, 137, 137)
                .addComponent(btnreset)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addComponent(lblgpa)
                .addGap(12, 12, 12)
                .addComponent(txtgpa, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblmarks)
                    .addComponent(lblcredithours))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubject1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcredit1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsubject1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubject2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcredit2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsubject2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubject3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcredit3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsubject3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubject4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcredit4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsubject4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubject5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcredit5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsubject5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtsubject6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtcredit6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblsubject6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblgpa)
                    .addComponent(txtgpa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btncalcgpa)
                    .addComponent(btnreset))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btncalcgpaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncalcgpaActionPerformed
        qp1 = qualitypoints(Integer.parseInt(txtsubject1.getText()), Integer.parseInt(txtcredit1.getText()));
        qp2 = qualitypoints(Integer.parseInt(txtsubject2.getText()), Integer.parseInt(txtcredit2.getText()));
        qp3 = qualitypoints(Integer.parseInt(txtsubject3.getText()), Integer.parseInt(txtcredit3.getText()));
        qp4 = qualitypoints(Integer.parseInt(txtsubject4.getText()), Integer.parseInt(txtcredit4.getText()));
        qp5 = qualitypoints(Integer.parseInt(txtsubject5.getText()), Integer.parseInt(txtcredit5.getText()));
        qp6 = qualitypoints(Integer.parseInt(txtsubject6.getText()), Integer.parseInt(txtcredit6.getText()));
        
        cre1 = Integer.parseInt(txtcredit1.getText());
        cre2 = Integer.parseInt(txtcredit2.getText());
        cre3 = Integer.parseInt(txtcredit3.getText());
        cre4 = Integer.parseInt(txtcredit4.getText());
        cre5 = Integer.parseInt(txtcredit5.getText());
        cre6 = Integer.parseInt(txtcredit6.getText());
        
        totalQualityPoints = qp1 + qp2 + qp3 + qp4 + qp5 + qp6;
        totalCreditHours = cre1 + cre2 + cre3 + cre4 + cre5 + cre6;
        
        gpa = totalQualityPoints/totalCreditHours;
        
        txtgpa.setText(String.valueOf(gpa));
    }//GEN-LAST:event_btncalcgpaActionPerformed

    private void btnresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnresetActionPerformed
        txtsubject1.setText("0");
        txtsubject2.setText("0");
        txtsubject3.setText("0");
        txtsubject4.setText("0");
        txtsubject5.setText("0");
        txtsubject6.setText("0");
        txtcredit1.setText("0");
        txtcredit2.setText("0");
        txtcredit3.setText("0");
        txtcredit4.setText("0");
        txtcredit5.setText("0");
        txtcredit6.setText("0");
    }//GEN-LAST:event_btnresetActionPerformed

    
    private double qualitypoints(int marks, int credits){
        if(credits == 2){
            if(marks == 16) qualityPoints = 2.0;
            else if(marks == 17) qualityPoints = 2.6;
            else if(marks == 18) qualityPoints = 3.0;
            else if(marks == 19) qualityPoints = 3.6;
            else if(marks == 20) qualityPoints = 4.0;
            else if(marks == 21) qualityPoints = 4.4;
            else if(marks == 22) qualityPoints = 4.6;
            else if(marks == 23) qualityPoints = 5.0;
            else if(marks == 24) qualityPoints = 5.4;
            else if(marks == 25) qualityPoints = 5.6;
            else if(marks == 26) qualityPoints = 6.0;
            else if(marks == 27) qualityPoints = 6.4;
            else if(marks == 28) qualityPoints = 6.6;
            else if(marks == 29) qualityPoints = 7.0;
            else if(marks == 30) qualityPoints = 7.4;
            else if(marks == 31) qualityPoints = 7.6;
            else if(marks >= 32 && marks <= 40) qualityPoints = 8.0;
        }
        else if(credits == 3){
            if(marks == 24) qualityPoints = 3.0;
            else if(marks == 25) qualityPoints = 3.6;
            else if(marks == 26) qualityPoints = 3.9;
            else if(marks == 27) qualityPoints = 4.5;
            else if(marks == 28) qualityPoints = 5.1;
            else if(marks == 29) qualityPoints = 5.4;
            else if(marks == 30) qualityPoints = 6.0;
            else if(marks == 31) qualityPoints = 6.3;
            else if(marks == 32) qualityPoints = 6.6;
            else if(marks == 33) qualityPoints = 6.9;
            else if(marks == 34) qualityPoints = 7.2;
            else if(marks == 35) qualityPoints = 7.5;
            else if(marks == 36) qualityPoints = 8.1;
            else if(marks == 37) qualityPoints = 8.4;
            else if(marks == 38) qualityPoints = 8.7;
            else if(marks == 39) qualityPoints = 9.0;
            else if(marks == 40) qualityPoints = 9.3;
            else if(marks == 41) qualityPoints = 9.6;
            else if(marks == 42) qualityPoints = 9.9;
            else if(marks == 43) qualityPoints = 10.2;
            else if(marks == 44) qualityPoints = 10.5;
            else if(marks == 45) qualityPoints = 11.1;
            else if(marks == 46) qualityPoints = 11.4;
            else if(marks == 47) qualityPoints = 11.7;
            else if(marks >= 48 && marks <= 60) qualityPoints = 12.0;
        }
        else if(credits == 4){
            if(marks == 32) qualityPoints = 4.0;
            else if(marks == 33) qualityPoints = 4.4;
            else if(marks == 34) qualityPoints = 5.2;
            else if(marks == 35) qualityPoints = 5.6;
            else if(marks == 36) qualityPoints = 6.0;
            else if(marks == 37) qualityPoints = 6.4;
            else if(marks == 38) qualityPoints = 7.2;
            else if(marks == 39) qualityPoints = 7.6;
            else if(marks == 40) qualityPoints = 8.0;
            else if(marks == 41) qualityPoints = 8.4;
            else if(marks == 42) qualityPoints = 8.8;
            else if(marks == 43) qualityPoints = 8.8;
            else if(marks == 44) qualityPoints = 9.2;
            else if(marks == 45) qualityPoints = 9.6;
            else if(marks == 46) qualityPoints = 10.0;
            else if(marks == 47) qualityPoints = 10.4;
            else if(marks == 48) qualityPoints = 10.8;
            else if(marks == 49) qualityPoints = 10.8;
            else if(marks == 50) qualityPoints = 11.2;
            else if(marks == 51) qualityPoints = 11.6;
            else if(marks == 52) qualityPoints = 12.0;
            else if(marks == 53) qualityPoints = 12.0;
            else if(marks == 54) qualityPoints = 12.4;
            else if(marks == 55) qualityPoints = 12.8;
            else if(marks == 56) qualityPoints = 13.2;
            else if(marks == 57) qualityPoints = 13.6;
            else if(marks == 58) qualityPoints = 14.0;
            else if(marks == 59) qualityPoints = 14.4;
            else if(marks == 60) qualityPoints = 14.8;
            else if(marks == 61) qualityPoints = 14.8;
            else if(marks == 62) qualityPoints = 15.2;
            else if(marks == 63) qualityPoints = 15.6;
            else if(marks >=64  && marks <= 80) qualityPoints = 16.0;
        }
        else if(credits == 5){
            if(marks == 40) qualityPoints = 5.0;
            else if(marks == 41) qualityPoints = 5.5;
            else if(marks == 42) qualityPoints = 6.0;
            else if(marks == 43) qualityPoints = 6.5;
            else if(marks == 44) qualityPoints = 7.0;
            else if(marks == 45) qualityPoints = 7.5;
            else if(marks == 46) qualityPoints = 8.0;
            else if(marks == 47) qualityPoints = 8.5;
            else if(marks == 48) qualityPoints = 9.0;
            else if(marks == 49) qualityPoints = 9.5;
            else if(marks == 50) qualityPoints = 10.0;
            else if(marks == 51) qualityPoints = 10.5;
            else if(marks == 52) qualityPoints = 10.5;
            else if(marks == 53) qualityPoints = 11.0;
            else if(marks == 54) qualityPoints = 11.5;
            else if(marks == 55) qualityPoints = 11.5;
            else if(marks == 56) qualityPoints = 12.0;
            else if(marks == 57) qualityPoints = 12.5;
            else if(marks == 58) qualityPoints = 12.5;
            else if(marks == 59) qualityPoints = 13.0;
            else if(marks == 60) qualityPoints = 13.5;
            else if(marks == 61) qualityPoints = 13.5;
            else if(marks == 62) qualityPoints = 14.0;
            else if(marks == 63) qualityPoints = 14.5;
            else if(marks == 64) qualityPoints = 14.5;
            else if(marks == 65) qualityPoints = 15.0;
            else if(marks == 66) qualityPoints = 15.5;
            else if(marks == 67) qualityPoints = 15.5;
            else if(marks == 68) qualityPoints = 16.0;
            else if(marks == 69) qualityPoints = 16.5;
            else if(marks == 70) qualityPoints = 16.5;
            else if(marks == 71) qualityPoints = 17.0;
            else if(marks == 72) qualityPoints = 17.5;
            else if(marks == 73) qualityPoints = 17.5;
            else if(marks == 74) qualityPoints = 18.0;
            else if(marks == 75) qualityPoints = 18.5;
            else if(marks == 76) qualityPoints = 18.5;
            else if(marks == 77) qualityPoints = 19.0;
            else if(marks == 78) qualityPoints = 19.5;
            else if(marks == 79) qualityPoints = 19.5;
            else if(marks >=80  && marks <= 100) qualityPoints = 20.0;
        }
        return qualityPoints;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CGPAGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CGPAGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CGPAGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CGPAGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CGPAGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncalcgpa;
    private javax.swing.JButton btnreset;
    private javax.swing.JLabel lblcredithours;
    private javax.swing.JLabel lblgpa;
    private javax.swing.JLabel lblmarks;
    private javax.swing.JLabel lblsubject1;
    private javax.swing.JLabel lblsubject2;
    private javax.swing.JLabel lblsubject3;
    private javax.swing.JLabel lblsubject4;
    private javax.swing.JLabel lblsubject5;
    private javax.swing.JLabel lblsubject6;
    private javax.swing.JTextField txtcredit1;
    private javax.swing.JTextField txtcredit2;
    private javax.swing.JTextField txtcredit3;
    private javax.swing.JTextField txtcredit4;
    private javax.swing.JTextField txtcredit5;
    private javax.swing.JTextField txtcredit6;
    private javax.swing.JTextField txtgpa;
    private javax.swing.JTextField txtsubject1;
    private javax.swing.JTextField txtsubject2;
    private javax.swing.JTextField txtsubject3;
    private javax.swing.JTextField txtsubject4;
    private javax.swing.JTextField txtsubject5;
    private javax.swing.JTextField txtsubject6;
    // End of variables declaration//GEN-END:variables
}
